# Generated by Django 4.0.4 on 2022-05-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_currency_alter_price_date_userstockinvestments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowedCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='main_currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='CurrencyExchangeRate',
        ),
    ]
