# Generated by Django 4.0.4 on 2022-06-09 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField(db_index=True)),
                ('buy', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.DeleteModel(
            name='UserStockInvestments',
        ),
        migrations.AddField(
            model_name='userstocktransactions',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company'),
        ),
        migrations.AddField(
            model_name='userstocktransactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
